// src/config/serfActionStates.js
export const SERF_ACTION_STATES = {
    IDLE: 'IDLE',
    MOVING_TO_TARGET: 'MOVING_TO_TARGET',
    // PERFORMING_TASK: 'PERFORMING_TASK', // Consider removing if too generic, covered by specific work states
    RETURNING_TO_DROPOFF: 'RETURNING_TO_DROPOFF',
    WORKING_AT_BUILDING: 'WORKING_AT_BUILDING', // For processing tasks inside buildings
    MOVING_TO_PICKUP_LOCATION: 'MOVING_TO_PICKUP_LOCATION',
    PICKING_UP_RESOURCE: 'PICKING_UP_RESOURCE',
    MOVING_TO_RESOURCE_DROPOFF: 'MOVING_TO_RESOURCE_DROPOFF',
    DROPPING_OFF_RESOURCE: 'DROPPING_OFF_RESOURCE',
    SEARCHING_FOR_RESOURCE_ON_MAP: 'SEARCHING_FOR_RESOURCE_ON_MAP',
    MOVING_TO_RESOURCE_NODE: 'MOVING_TO_RESOURCE_NODE',
    GATHERING_RESOURCE_FROM_NODE: 'GATHERING_RESOURCE_FROM_NODE',
    MOVING_TO_DEPOSIT_BUILDING: 'MOVING_TO_DEPOSIT_BUILDING',
    DEPOSITING_RESOURCE_IN_BUILDING: 'DEPOSITING_RESOURCE_IN_BUILDING',

    // New States from Plan:
    PLANTING_SAPLING: 'PLANTING_SAPLING', // Forester
    FISHING: 'FISHING', // Fisherman
    // MILLING_GRAIN, BAKING_BREAD, etc. will be handled by WORKING_AT_BUILDING with specific logic in Serf class based on building.info
    // PROCESSING_WOOD, SLAUGHTERING_PIGS also handled by WORKING_AT_BUILDING
    RAISING_PIGS: 'RAISING_PIGS', // Pig Farmer (might involve MOVING_TO_TARGET for grain, then WORKING_AT_BUILDING)
    FARMING_PLANTING: 'FARMING_PLANTING', // Farmer
    FARMING_TENDING: 'FARMING_TENDING', // Farmer (waiting for growth)
    FARMING_HARVESTING: 'FARMING_HARVESTING', // Farmer
    PROSPECTING: 'PROSPECTING', // Geologist (future)
    CONSTRUCTING_BUILDING: 'CONSTRUCTING_BUILDING', // Builder
    MOVING_TO_TARGET_TILE: 'MOVING_TO_TARGET_TILE', // For tasks like planting sapling/crops at a specific tile
};
