// src/config/serfProfessions.js
export const SERF_PROFESSIONS = {
    TRANSPORTER: 'Transporter',
    BUILDER: 'Builder',
    WOODCUTTER: 'Woodcutter',
    FORESTER: 'Forester',
    STONEMASON: 'Stonemason',
    MINER: 'Miner',
    FARMER: 'Farmer',
    FISHERMAN: 'Fisherman',
    MILLER: 'Miller',
    BAKER: 'Baker',
    PIG_FARMER: 'Pig Farmer',
    BUTCHER: 'Butcher',
    SAWMILL_WORKER: 'Sawmill Worker',
    SMELTER_WORKER: 'Smelter Worker',
    GOLDSMITH: 'Goldsmith',
    TOOLMAKER: 'Toolmaker',
    BLACKSMITH: 'Blacksmith',
    GEOLOGIST: 'Geologist',
    HUNTER: 'Hunter',
    HERBALIST: 'Herbalist',
    TRAPPER: 'Trapper',
    TANNER: 'Tanner',
    CRAFTSMAN: 'Craftsman',
    MERCHANT: 'Merchant',
    COOK: 'Cook',
    ALCHEMIST: 'Alchemist',
    BREWER: 'Brewer',
    WEAVER: 'Weaver',
    TAILOR: 'Tailor',
    FLETCHER: 'Fletcher',
    BOWYER: 'Bowyer',
    ARMORER: 'Armorer',
    CANDLEMAKER: 'Candlemaker',
    GLASSBLOWER: 'Glassblower',
    POTTER: 'Potter',
    CARTOGRAPHER: 'Cartographer',
    SAILMAKER: 'Sailmaker',
    SHIPWRIGHT: 'Shipwright',
    GUARD: 'Guard',
    SENTRY: 'Sentry',
    WATCHMAN: 'Watchman',
    SCHOLAR: 'Scholar',
    TEACHER: 'Teacher',
    CLERIC: 'Cleric',
    PRIEST: 'Priest',
    MONK: 'Monk',
    APOSTLE: 'Apostle',
    MISSIONARY: 'Missionary',
    DIPLOMAT: 'Diplomat',
    SPY: 'Spy',
    ASSASSIN: 'Assassin',
    ENGINEER: 'Engineer',
    ALCHEMICAL_ENGINEER: 'Alchemical Engineer',
    ARCHITECT: 'Architect',
    INVENTOR: 'Inventor',
    ARTISAN: 'Artisan',
    CULTIVATOR: 'Cultivator',
    VINTNER: 'Vintner',
    BREEDER: 'Breeder',
    FURRIER: 'Furrier',
    JEWELER: 'Jeweler',
    ENCHANTER: 'Enchanter',
    TINKER: 'Tinker',
    SCRIBE: 'Scribe',
    CALLIGRAPHER: 'Calligrapher',
    ILLUMINATOR: 'Illuminator',
    HISTORIAN: 'Historian',
    POET: 'Poet',
    MUSICIAN: 'Musician',
    ACTOR: 'Actor',
    DANCER: 'Dancer',
    ASTRONOMER: 'Astronomer',
    ALCHEMIST_ASSISTANT: 'Alchemist Assistant'
};
