// src/config/serfActionStates.js
export const SERF_ACTION_STATES = {
    IDLE: 'IDLE',
    MOVING_TO_TARGET: 'MOVING_TO_TARGET',
    PERFORMING_TASK: 'PERFORMING_TASK',
    RETURNING_TO_DROPOFF: 'RETURNING_TO_DROPOFF',
    WORKING_AT_BUILDING: 'WORKING_AT_BUILDING',
    MOVING_TO_PICKUP_LOCATION: 'MOVING_TO_PICKUP_LOCATION',
    PICKING_UP_RESOURCE: 'PICKING_UP_RESOURCE',
    MOVING_TO_RESOURCE_DROPOFF: 'MOVING_TO_RESOURCE_DROPOFF',
    DROPPING_OFF_RESOURCE: 'DROPPING_OFF_RESOURCE',
    SEARCHING_FOR_RESOURCE_ON_MAP: 'SEARCHING_FOR_RESOURCE_ON_MAP',
    MOVING_TO_RESOURCE_NODE: 'MOVING_TO_RESOURCE_NODE',
    GATHERING_RESOURCE_FROM_NODE: 'GATHERING_RESOURCE_FROM_NODE',
    MOVING_TO_DEPOSIT_BUILDING: 'MOVING_TO_DEPOSIT_BUILDING',
    DEPOSITING_RESOURCE_IN_BUILDING: 'DEPOSITING_RESOURCE_IN_BUILDING',
};
